theme: jekyll-theme-minimal
github:
  is_project_page: false
  is_user_page: true

description:  PhD Student in Natural Language Processing (NLP) and Digital Humanities, 
              with special interest in <i>historical languages</i> and <i>linguistic knowledge representation</i>.
              </br>I am part of the interdiciplinary research project "Script and Text in Time and Place"
              at the University of Copenhagen.
              

title: Sidsel Boldsen
logo: assets/misc/Nala-the-cat-shark-hat.jpg